[package]
name = "ceph-safe-disk"
version = "0.1.0"
authors = ["Alberto Corona <ac@albertocorona.com>"]

[dependencies]
getopts = "~0.2"
ansi_term = "~0.9"
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
users = "~0.5"

[lib]
name = "ceph"
path = "lib/lib.rs"
